name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract repository name
        id: repo
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            --label "org.opencontainers.image.authors=${{ github.actor }}" \
            --label "org.opencontainers.image.title=${{ env.REPO }}" \
            --label "org.opencontainers.image.source=https://github.com/${{ env.REPO }}" \
            -t ghcr.io/${{ env.REPO }}/spa-records-app:latest \
            -t ghcr.io/${{ env.REPO }}/spa-records-app:${{ github.sha }} \
            .

      - name: Push Docker image (latest)
        run: docker push ghcr.io/${{ env.REPO }}/spa-records-app:latest

      - name: Push Docker image (commit SHA)
        run: docker push ghcr.io/${{ env.REPO }}/spa-records-app:${{ github.sha }}

