name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - master
      - Experimental

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract repository name
        id: repo
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set image tag
        id: tag
        run: |
          if [[ "${GITHUB_REF##*/}" == "master" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "experimental" ]]; then
            echo "TAG=experimental" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build \
            --label "org.opencontainers.image.authors=${{ github.actor }}" \
            --label "org.opencontainers.image.title=${{ env.REPO }}" \
            --label "org.opencontainers.image.source=https://github.com/${{ env.REPO }}" \
            -t ghcr.io/${{ env.REPO }}:${{ env.TAG }} \
            -t ghcr.io/${{ env.REPO }}:${{ github.sha }} \
            .

      - name: Push Docker image (branch tag)
        run: docker push ghcr.io/${{ env.REPO }}:${{ env.TAG }}

      - name: Push Docker image (commit SHA)
        run: docker push ghcr.io/${{ env.REPO }}:${{ github.sha }}
